sendbird/sendbird-chat-sdk-ios

Gemfile, Gemfile.lock
Update gemfile to fix release build error
```
Your Gemfile has no gem server sources. If you need gems that are not already on
your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find concurrent-ruby-1.1.10 in any of the sources
```
=> [CLN-520] Update gemfile

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
- Resolved the inconsistency between WebSocket connection state and network reachability
- Fixed a crash that can happen when SessionExpiredEvent is received
- Improved stability
=> Release/4.9.5 -> master

SendbirdChatSDK.podspec
=> Release - 4.11.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.12.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.12.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.12.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.12.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.13.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.13.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.14.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.14.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.14.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.15.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.15.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.15.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.15.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.15.4

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.16.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.16.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.17.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.18.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.1

generate_podspec.sh
=> [CLNP-2592] Removed v from tag

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.4

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.5

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.6

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.7

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.8

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.19.9

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.20.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.4

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.5

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.6

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.7

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.8

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.9

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.21.10

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.22.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.22.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.23.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.23.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.23.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.24.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.24.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.24.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.24.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.4

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.5

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.6

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.7

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.25.8

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.26.0

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.26.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.27.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.27.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.27.3

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.28.1

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 4.29.2

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
=> Release 1.2.100

CHANGELOG.md, Package.swift, SendbirdChatSDK.podspec
Reverts sendbird/sendbird-chat-sdk-ios#111
=> Revert "Release 1.2.100"
